export const todoTypes = {
    FETCH_TODOS : "FETCH_TODOS",
    ADD_TODO: "ADD_TODO",
    DELETE_TODO: "DELETE_TODO",
    UPDATE_TODO: "UPDATE_TODO",
    SET_DISPLAY: "SET_DISPLAY",
    SET_MODE: "SET_MODE",
}