export const todoTypes = {
    FETCH_TODOS_REQUEST : "FETCH_TODOS_REQUEST",
    FETCH_TODOS_SUCCESS : 'FETCH_TODOS_SUCCESS',
    FETCH_TODOS_FAILURE : 'FETCH_TODOS_SUCCESS',
    ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
    DELETE_TODO_SUCCESS: "DELETE_TODO_SUCCESS",
    UPDATE_TODO_SUCCES: "UPDATE_TODO_SUCCES"
}